### ISSUE TITLE
Get 404 not found when using Upgrade Helper

### ISSUE THREAD

**Issue by tonsnoei** [react-native-community/rn-diff-purge#53] opened 2021-11-17 14:51 UTC
Go to: https://react-native-community.github.io/upgrade-helper/?from=0.63.4&to=0.66.2
Press: View File
Result: 404 not found
![2021-11-17_15-47-39](https://user-images.githubusercontent.com/8810118/142223279-35313fd7-90ba-4f3c-9288-69530150e78d.png)

![2021-11-17_15-49-05](https://user-images.githubusercontent.com/8810118/142223263-c932e6b5-d8db-4d71-acd1-a71720498078.png)

**Comment by pvinis** [comment] 2022-06-01 17:43
seems like the issue is fixed in https://github.com/ecomfe/gitdiff-parser/pull/25/files, which is a dep of a dep.

you can find the right file by changing the url from `../DiffApp/..` to `../RnDiffApp/..`.

**Closed** 2022-11-12 04:24 UTC
